#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json
packaging_format = 2

id = "phpboost"
name = "PHPBoost"
description.en = "French and free content management system (CMS)"
description.fr = "Système de gestion de contenu (CMS) français et libre"

version = "6.0.4~ynh1"

maintainers = []

[upstream]
license = "GPL-3.0-only"
website = "https://www.phpboost.com/"
demo = "https://demo.phpboost.com/"
admindoc = "https://www.phpboost.com/wiki/wiki.php"
code = "https://github.com/PHPBoost/PHPBoost"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "253M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/phpboost"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/PHPBoost/PHPBoost/archive/refs/tags/phpboost-6.0.4.tar.gz"
        sha256 = "b6907bf7e275d67f5c9fda99af26b2b056ba15a17c86019a0131fa1e8f52ad8d"
        autoupdate.strategy = "latest_github_release"
        autoupdate.version_regex = "phpboost-(.*)"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.2-mysql, php8.2-gd, php8.2-mbstring"

    [resources.database]
    type = "mysql"
