packaging_format = 2

id = "phpboost"
name = "PHPBoost"
description.en = "French and free content management system (CMS)"
description.fr = "système de gestion de contenu (CMS) français et libre"

version = "5.2.11~ynh2"

maintainers = [""]

[upstream]
license = "GPL-3.0-only"
website = "https://www.phpboost.com/"
demo = "https://demo.phpboost.com/"
admindoc = "https://www.phpboost.com/wiki/wiki.php"
code = "https://github.com/PHPBoost/PHPBoost"

[integration]
yunohost = ">= 11.1.11"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "253M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/phpboost"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server php7.4-mysql php7.4-gd"

    [resources.database]
    type = "mysql"
