#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

#domain=$(ynh_app_setting_get $app domain)
domain=$(ynh_app_setting_get --app=$app --key=domain)

#port=$(ynh_app_setting_get $app port)

#final_path=$(ynh_app_setting_get $app final_path)
final_path=$(ynh_app_setting_get --app=$app --key=final_path)

#=================================================
# STANDARD REMOVE
#=================================================

ynh_package_remove emby-server

#=================================================
# REMOVE DEPENDENCIES
#=================================================

# Remove metapackage and its dependencies
#ynh_remove_app_dependencies

#=================================================
# REMOVE APP MAIN DIR
#=================================================

# Remove the app directory securely
#ynh_secure_remove "$final_path"
ynh_secure_remove --file="$final_path"

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================

# Remove the dedicated nginx config
ynh_remove_nginx_config

#=================================================
# CLOSE A PORT
#=================================================

#if yunohost firewall list | grep -q "\- $port$"
#then
#	ynh_script_progression --message="Closing port $port..." --time --weight=1
#	ynh_exec_warn_less yunohost firewall disallow TCP $port
#fi

#=================================================
# SPECIFIC REMOVE
#=================================================
# REMOVE THE CRON FILE
#=================================================

# Remove a cron file
#ynh_secure_remove "/etc/cron.d/$app"
ynh_secure_remove --file="/etc/cron.d/$app"

# Remove a directory securely
#ynh_secure_remove "/etc/apt/sources.list.d/onlyoffice.list"
ynh_secure_remove --file="/etc/$app/"

# Remove the log files
#ynh_secure_remove "/var/log/$app/"
ynh_secure_remove --file="/var/log/$app/"

#=================================================
# GENERIC FINALIZATION
#=================================================
# REMOVE DEDICATED USER
#=================================================

# Delete a system user
#ynh_system_user_delete $app
ynh_system_user_delete --username=$app

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --time --last
